import nodemailer from "nodemailer";

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

transporter.verify((error) => {
  if (error) {
    console.log("SMTP Error:", error);
  } else {
    console.log("SMTP Connected Successfully");
  }
});

export const sendResetEmail = async (
  email: string,
  resetLink: string
) => {
  try {
    const info = await transporter.sendMail({
      from: process.env.EMAIL_USER,
      to: email,
      subject: "Reset Your Password",

      html: `
        <h2>Reset Password</h2>

        <p>Hello,</p>

        <p>Click the button below to reset your password.</p>

        <a href="${resetLink}"
           style="
             background:#1976d2;
             color:white;
             padding:12px 20px;
             text-decoration:none;
             border-radius:5px;
             display:inline-block;
             font-weight:bold;">
          Reset Password
        </a>

        <br><br>

        <p>If the button does not work, copy and paste the link below:</p>

        <textarea rows="2" cols="70" readonly>${resetLink}</textarea>

        <br><br>

        <p>This link was generated by the Forgot Password system.</p>
      `,
    });

    console.log("Email Sent Successfully");
    console.log(info.response);
  } catch (err) {
    console.error("Email Send Error:", err);
    throw err;
  }
};